language: java

before_deploy:
      - git config --local user.name "Nutty101"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
      
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "NPC_Police-2.2-$TRAVIS_TAG.zip"
  skip_cleanup: true

